[package]
name = "ti-smoked"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure_identity = "0.9.0"
reqwest = { version = "0.11.13", features = ["blocking"] }
serde = { version = "1.0.151",  features = ["derive"] }
serde_json = "1.0.91"

[profile.dev]
opt-level = 3
